import { test, expect } from "@playwright/test";
import { Login } from "../src/ScreenPLay/Tasks/Login";
import { VerifyProducts } from "../src/ScreenPLay/Tasks/VerifyProducts";
import { LoginResponse } from "../src/ScreenPLay/Questions/LoginResponse";
import { AIService } from "../src/ScreenPLay/Models/AIService";


test("Login in Sauce Demo with credentials generated by AI", async ({ page }) => {
    await page.goto("https://www.saucedemo.com/");

    const responseText = await Login.AICredentials(page);
    const aiLoginResponse = await AIService.AnalyzeResponse(responseText || "Successfull Login, Products Displayed.");
    console.log("📌 AI analysis (Login):", aiLoginResponse);

    if (LoginResponse.IsSuccessfull(responseText)) {
        await expect(page.locator(".inventory_list")).toBeVisible();
        await VerifyProducts.AnalyzeName(page);
        await VerifyProducts.AnalyzeDrescption(page);
    } else {
        await expect(page.locator(".error-message-container")).toBeVisible();
    }
});
